version: "3.9"

services:
  api:
    container_name: api
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - PORT=3002
    ports:
      - 3002:3002
    depends_on:
      db:
        condition: service_healthy
    command: "yarn dev"
    volumes:
      - .:/api

  db:
    container_name: db
    image: postgres:12-alpine
    ports:
      - 5431:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=defaultdb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d defaultdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - api
    command: "yarn start"
    volumes:
      - .:/frontend
